MODEL:
  MAX_INPUT_TOKENS: 512
  MAX_OUTPUT_TOKENS: 64
  TOKENIZER_NAME: "t5-small"
  PRETRAINED_MODEL_NAME: "t5-small"
  PATH_TO_CHECKPOINT: "storage/checkpoints/pretrained_totto/ablation/no_type/full_entities/t5_small/epoch=0-step=15144.ckpt"

SOLVER:
  OPTIMIZER_NAME: "AdaFactor"
  BASE_LR: 0.001

WANDB:
  RUN_NAME: "Inference Curated No Injection Cordis Annotation | With query info"
  GROUP: "No Type | Full Entities ToTTo Dataset | T5-small"
  TAGS: ["Evaluate", "Curated", "Cordis", "t5-small"]
  MODE: "online"
  NOTES: ""

DATASET:
  VALIDATION: "storage/datasets/totto/cordis_to_totto/curated_no_injection_cordis_with_query.json"
  EVALUATION: "storage/datasets/totto/cordis_to_totto/curated_no_injection_cordis_with_query.json"
  TRAIN: "storage/datasets/totto/filtered_sampled/train.json"

DATALOADER:
  NUM_WORKERS: 11

INPUT:
  TRAIN_BATCH_SIZE: 8
  TEST_BATCH_SIZE: 8
