MODEL:
  MAX_INPUT_TOKENS: 512
  MAX_OUTPUT_TOKENS: 64
  TOKENIZER_NAME: "t5-base"
  PRETRAINED_MODEL_NAME: "t5-base"
  PATH_TO_CHECKPOINT: "storage/checkpoints/pretrained_totto/all_tasks/full_entities/t5_base/epoch=0-step=15144.ckpt"

SOLVER:
  OPTIMIZER_NAME: "AdaFactor"
  BASE_LR: 0.001

WANDB:
  RUN_NAME: "cordis"
  GROUP: "CI | ARIS | T5-base | QR2T"
  MODE: "offline"
  NOTES: ""

DATASET:
  VALIDATION: "storage/datasets/compact_input/cordis/curated_cordis_with_query.json"
  EVALUATION: "storage/datasets/compact_input/cordis/curated_cordis_with_query.json"
  TRAIN: "storage/datasets/compact_input/totto/filtered_sampled/train.json"

DATALOADER:
  NUM_WORKERS: 11

INPUT:
  TRAIN_BATCH_SIZE: 7
  TEST_BATCH_SIZE: 7
