MODEL:
  MAX_INPUT_TOKENS: 512
  MAX_OUTPUT_TOKENS: 64
  TOKENIZER_NAME: "t5-small"
  PRETRAINED_MODEL_NAME: "t5-small"
  PATH_TO_CHECKPOINT: ""

SOLVER:
  OPTIMIZER_NAME: "AdaFactor"
  BASE_LR: 0.001
  CHECKPOINT_PERIOD: 5000
  MAX_EPOCHS: 1

WANDB:
  RUN_NAME: "Pretrain t5-small | All pretrain tasks"
  GROUP: "Pretrain"
  TAGS: ["Pretrain", "t5-small"]
  MODE: "online"
  NOTES: ""

DATASET:
  VALIDATION: ""
  EVALUATION: ""
  TRAIN: "storage/datasets/pretrain/all_tasks/pretrain_file_0.json"

DATALOADER:
  NUM_WORKERS: 11

INPUT:
  TRAIN_BATCH_SIZE: 8
  TEST_BATCH_SIZE: 8

OUTPUT:
  CHECKPOINTS_DIR: "storage/checkpoints/pretrained/all_tasks/t5_small/"
