MODEL:
  MAX_INPUT_TOKENS: 512
  MAX_OUTPUT_TOKENS: 64
  TOKENIZER_NAME: "t5-small"
  PRETRAINED_MODEL_NAME: "t5-small"
  PATH_TO_CHECKPOINT: "storage/checkpoints/aris/compact_input/ablations/only_one/original_task/finetune/evaluation/aux_totto_qr2t/epoch=4-step=259.ckpt"

SOLVER:
  OPTIMIZER_NAME: "AdaFactor"
  BASE_LR: 0.001

WANDB:
  RUN_NAME: "cordis"
  GROUP: "Only original task | CI | ARIS | T5-small | Pretrain | ToTTo | QR2T"
  MODE: "online"
  NOTES: ""

DATASET:
  VALIDATION: "storage/datasets/compact_input/cordis/curated_cordis_with_query.json"
  EVALUATION: "storage/datasets/compact_input/cordis/curated_cordis_with_query.json"
  TRAIN: "storage/datasets/compact_input/totto/filtered_sampled/train.json"

DATALOADER:
  NUM_WORKERS: 11

INPUT:
  TRAIN_BATCH_SIZE: 8
  TEST_BATCH_SIZE: 8
