MODEL:
  MAX_INPUT_TOKENS: 512
  MAX_OUTPUT_TOKENS: 64
  TOKENIZER_NAME: "t5-base"
  PRETRAINED_MODEL_NAME: "t5-base"
  PATH_TO_CHECKPOINT: "storage/checkpoints/main_experiments/pretrained/t5_base/epoch=0-step=79999.ckpt"

OUTPUT:
  CHECKPOINTS_DIR: "storage/checkpoints/main_experiments/finetuned/t5_base/pretrained_qr2t"

SOLVER:
  OPTIMIZER_NAME: "AdaFactor"
  BASE_LR: 0.001
  MAX_EPOCHS: 10


DATASET:
  TRAIN: "storage/datasets/qr2t/train.json"
  VALIDATION: "storage/datasets/qr2t/eval.json"
#  EVALUATION: "storage/datasets/totto/filtered/evaluation.json"

WANDB:
  RUN_NAME: "Finetune"
  GROUP: "ARIS | T5-base | Pretrain | QR2T"
  MODE: "offline"
  NOTES: ""

DATALOADER:
  NUM_WORKERS: 11

INPUT:
  TRAIN_BATCH_SIZE: 24
  TEST_BATCH_SIZE: 24
