MODEL:
  MAX_INPUT_TOKENS: 512
  MAX_OUTPUT_TOKENS: 64
  TOKENIZER_NAME: "t5-small"
  PRETRAINED_MODEL_NAME: "t5-small"
  PATH_TO_CHECKPOINT: "storage/checkpoints/aris/compact_input/finetuned/t5_small/pretrained_qr2t/epoch=4-step=259.ckpt"

#OUTPUT:
#  CHECKPOINTS_DIR: "storage/checkpoints/full_entities/t5_small"

SOLVER:
  OPTIMIZER_NAME: "AdaFactor"
  BASE_LR: 0.001

DATASET:
  TRAIN: "storage/datasets/compact_input/totto/train.json"
  VALIDATION: "storage/datasets/compact_input/totto/dev.json"
  EVALUATION: "storage/datasets/compact_input/totto/evaluation.json"

WANDB:
  RUN_NAME: "totto"
  GROUP: "No column mixing | CI | ARIS | T5-small | Pretrain | ToTTo | QR2T"
  MODE: "online"
  NOTES: ""

DATALOADER:
  NUM_WORKERS: 11

INPUT:
  TRAIN_BATCH_SIZE: 8
  TEST_BATCH_SIZE: 8
