MODEL:
  MAX_INPUT_TOKENS: 512
  MAX_OUTPUT_TOKENS: 64
  TOKENIZER_NAME: "t5-base"
  PRETRAINED_MODEL_NAME: "t5-base"
  PATH_TO_CHECKPOINT: "/users/pa21/mxydas/projects/Data2Text/storage/checkpoints/compact_input/pretrained/t5_base/epoch=0-step=44999.ckpt"

OUTPUT:
  CHECKPOINTS_DIR: "storage/checkpoints/compact_input/finetuned/t5_base/pretrained_totto"

SOLVER:
  OPTIMIZER_NAME: "AdaFactor"
  BASE_LR: 0.001
  MAX_EPOCHS: 10


DATASET:
  TRAIN: "storage/datasets/compact_input/totto/train.json"
  VALIDATION: "storage/datasets/compact_input/totto/dev.json"
#  EVALUATION: "storage/datasets/compact_input/totto/filtered/evaluation.json"

WANDB:
  RUN_NAME: "Finetune"
  GROUP: "CI | ARIS | T5-base | Pretrain | ToTTo"
  MODE: "offline"
  NOTES: ""

DATALOADER:
  NUM_WORKERS: 11

INPUT:
  TRAIN_BATCH_SIZE: 7
  TEST_BATCH_SIZE: 7
