MODEL:
  MAX_INPUT_TOKENS: 512
  MAX_OUTPUT_TOKENS: 64
  TOKENIZER_NAME: "t5-base"
  PRETRAINED_MODEL_NAME: "t5-base"
  PATH_TO_CHECKPOINT: ""

OUTPUT:
  CHECKPOINTS_DIR: "storage/checkpoints/compact_input/finetuned/t5_base/totto"

SOLVER:
  OPTIMIZER_NAME: "AdaFactor"
  BASE_LR: 0.001
  MAX_EPOCHS: 10


DATASET:
  TRAIN: "storage/datasets/totto/train.json"
  VALIDATION: "storage/datasets/totto/dev.json"
#  EVALUATION: "storage/datasets/totto/filtered/evaluation.json"

WANDB:
  RUN_NAME: "Finetune"
  GROUP: "CI | ARIS | T5-base | ToTTo"
  MODE: "offline"
  NOTES: ""

DATALOADER:
  NUM_WORKERS: 11

INPUT:
  TRAIN_BATCH_SIZE: 7
  TEST_BATCH_SIZE: 7
