MODEL:
  MAX_INPUT_TOKENS: 512
  MAX_OUTPUT_TOKENS: 64
  TOKENIZER_NAME: "t5-small"
  PRETRAINED_MODEL_NAME: "t5-small"
  PATH_TO_CHECKPOINT: ""

OUTPUT:
  CHECKPOINTS_DIR: "storage/checkpoints/compact_input/ablations/no_nl_query/totto/"

SOLVER:
  OPTIMIZER_NAME: "AdaFactor"
  BASE_LR: 0.001
  MAX_EPOCHS: 7


DATASET:
  TRAIN: "storage/datasets/compact_input/ablation/no_nl_query/totto/train.json"
  VALIDATION: "storage/datasets/compact_input/ablation/no_nl_query/totto/dev.json"
#  EVALUATION: "storage/datasets/compact_input/totto/filtered/evaluation.json"

WANDB:
  RUN_NAME: "Finetune"
  GROUP: "No NL Query | CI | ARIS | T5-small | ToTTo"
  MODE: "offline"
  NOTES: ""

DATALOADER:
  NUM_WORKERS: 11

INPUT:
  TRAIN_BATCH_SIZE: 24
  TEST_BATCH_SIZE: 24
