MODEL:
  MAX_INPUT_TOKENS: 512
  MAX_OUTPUT_TOKENS: 64
  TOKENIZER_NAME: "t5-base"
  PRETRAINED_MODEL_NAME: "t5-base"
  PATH_TO_CHECKPOINT: ""

SOLVER:
  OPTIMIZER_NAME: "AdaFactor"
  BASE_LR: 0.001
  CHECKPOINT_PERIOD: 5000
  MAX_EPOCHS: 1

WANDB:
  RUN_NAME: "Pretrain t5-base | All pretrain tasks"
  GROUP: "CI | ARIS | Pretrain"
  TAGS: ["ci", "pretrain", "t5-base", "aris"]
  MODE: "offline"
  NOTES: ""

DATASET:
  VALIDATION: ""
  EVALUATION: ""
  TRAIN: "storage/datasets/compact_input/auxiliary/totto_auxiliary_tasks_file_0.json"

DATALOADER:
  NUM_WORKERS: 11

INPUT:
  TRAIN_BATCH_SIZE: 7
  TEST_BATCH_SIZE: 7

OUTPUT:
  CHECKPOINTS_DIR: "storage/checkpoints/pretrained/all_tasks/t5_base/"
