MODEL:
  MAX_INPUT_TOKENS: 512
  MAX_OUTPUT_TOKENS: 64
  TOKENIZER_NAME: "t5-small"
  PRETRAINED_MODEL_NAME: "t5-small"
  PATH_TO_CHECKPOINT: "/users/pa21/mxydas/projects/Data2Text/storage/checkpoints/compact_input/pretrained/t5_small/epoch=0-step=14999.ckpt"

OUTPUT:
  CHECKPOINTS_DIR: "storage/checkpoints/compact_input/finetuned/t5_small/pretrained_qr2t"

SOLVER:
  OPTIMIZER_NAME: "AdaFactor"
  BASE_LR: 0.001
  MAX_EPOCHS: 7


DATASET:
  TRAIN: "storage/datasets/compact_input/qr2t/train.json"
  VALIDATION: "storage/datasets/compact_input/qr2t/dev.json"
#  EVALUATION: "storage/datasets/compact_input/totto/filtered/evaluation.json"

WANDB:
  RUN_NAME: "Finetune"
  GROUP: "CI | ARIS | T5-small | Pretrain | QR2T"
  MODE: "offline"
  NOTES: ""

DATALOADER:
  NUM_WORKERS: 11

INPUT:
  TRAIN_BATCH_SIZE: 24
  TEST_BATCH_SIZE: 24
