MODEL:
  MAX_INPUT_TOKENS: 512
  MAX_OUTPUT_TOKENS: 64
  TOKENIZER_NAME: "t5-small"
  PRETRAINED_MODEL_NAME: "t5-small"
  PATH_TO_CHECKPOINT: "storage/checkpoints/main_experiments/finetuned/t5_small/totto/epoch=6-step=35342.ckpt"

SOLVER:
  OPTIMIZER_NAME: "AdaFactor"
  BASE_LR: 0.001

WANDB:
  RUN_NAME: "cordis"
  GROUP: "ARIS | T5-small | ToTTo"
  MODE: "offline"
  NOTES: ""

DATASET:
  VALIDATION: "storage/datasets/cordis/curated_cordis_with_query.json"
  EVALUATION: "storage/datasets/cordis/curated_cordis_with_query.json"
  TRAIN: "storage/datasets/totto/filtered_sampled/train.json"

DATALOADER:
  NUM_WORKERS: 11

INPUT:
  TRAIN_BATCH_SIZE: 24
  TEST_BATCH_SIZE: 24
